#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tpm2-simulator
Version  : 1
Release  : 2
URL      : https://sourceforge.net/projects/ibmswtpm2/files/ibmtpm974.tar.gz
Source0  : https://sourceforge.net/projects/ibmswtpm2/files/ibmtpm974.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : CPL-1.0
Requires: tpm2-simulator-bin = %{version}-%{release}
BuildRequires : openssl-dev
Patch1: 0001-TPMSimulator-fix-compile-issue-for-clear-linux.patch

%description
No detailed description available

%package bin
Summary: bin components for the tpm2-simulator package.
Group: Binaries

%description bin
bin components for the tpm2-simulator package.


%prep
%setup -q -n src
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1541407822
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1541407822
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tpm_server
